global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:

  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'kafka-1:7071'
          - 'kafka-2:7071'
          - 'kafka-3:7071'

  - job_name: 'kafka-exporter'
    static_configs:
      - targets:
          - 'kafka-exporter:9308'